[images]
  remote_images = [
    "https://ext.same-assets.com/**"
  ]

[build]
  command = "bun run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NODE_OPTIONS = "--max-old-space-size=4096"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
